services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: anchoring-pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: anchoring
      POSTGRES_PASSWORD: anchoring
      POSTGRES_DB: anchoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anchoring"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: anchoring_postgres_data