services:
  chroma:
    image: chromadb/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - /path/to/anchoring/.chroma:/data
    ports:
      - "8001:8000"
